### ISSUE TITLE
TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link_gt (parent world) at time 7.293018 according to authority unknown_publisher

### ISSUE THREAD

**Issue by zszz3** [MIT-SPARK/Khronos#11]
Thanks for your great work，But when i try to run your code，i meet the below problem，the rosbag i use is your download link。
![image](https://github.com/user-attachments/assets/cd13f516-bf4f-4b0d-a304-1f921f45b079)

**Comment by Schmluk** [comment]
Hi @zszz3 

Thanks for your interest and for reaching out! 

The error you are getting means Khronos has not been compiled or the workspace was not sourced.
The TF repeated data warning can safely be ignored (it is an artifact of the simulator). If the print is bothering you there are options to throttle the printing through tf, e.g. [see this Q&A](https://robotics.stackexchange.com/questions/99446/suppress-tf-repeated-data-warnings).

Hope this helps!
