### ISSUE TITLE
Is there a way to run Khronos on our custom data?

### ISSUE THREAD

**Issue by Anniebhalla10** [MIT-SPARK/Khronos#12]

**Comment by Schmluk** [comment]
Hi @Anniebhalla10,

Yes, by feeding it similar inputs as in the simulation case (i.e. RGB+D+Semantic images, with poses (through TF preferred)).

We will soon release an example running on only RGB-D data, that might be helpful for your use case.

Hope this helps!

**Comment by Anniebhalla16** [comment]
Have we already got an example running on RGB-D data?
Any updates on this?

Thank you in advance for your help :)
