### ISSUE TITLE
`develop` branch for some of the dependencies are not public

### ISSUE THREAD

**Issue by YuePanEdward** [MIT-SPARK/Khronos#3]
Thanks for your great work.

When cloning the dependencies:
```
vcs import . < khronos/install/ssh.rosinstall
```
It seems that the `develop` branches for some of the dependencies are not public yet.

```
Could not checkout ref 'develop': fatal: invalid reference: develop
```

**Comment by Schmluk** [comment]
Hi @YuePanEdward ,

Thanks a lot for pointing this out and your interest in Khronos! We'll push a fix momentarily (these should point to main).

**Comment by marcusabate** [comment]
Resolved, @YuePanEdward try latest main!
