### ISSUE TITLE
Question about semantic labels in the scene graph

### ISSUE THREAD

**Issue by kazumaobata** [MIT-SPARK/Khronos#7]
Hello, Khronos is very interesting research. The nodes in the scene graph that are projected in Rviz have labels like 'O(0)' and 'O(1)', but is it possible to assign semantic labels such as 'chair' or 'table' to the scene graph? Alternatively, can they be obtained from some ROS topic?

**Comment by Schmluk** [comment]
Hi @kazumaobata 

Thanks for reaching out and for your interest! Objects in Khronos do have a semantic label, it's just not printed by default. The 'O(1)' etc that you see is the node ID in the scene graph. You can access the semantic information by looking through the node attributes in the `DynamicSceneGraph` data structure. From there you can print, publish, visualize, or use them in any way you want.

Hope this helps!

**Comment by kazumaobata** [comment]
Thank you for your response!
It worked out!

**Comment by Schmluk** [comment]
Geat to hear!
